#pragma once

#include <cstdint>

// Embedded Earth map, generated by scripts/gen_earth_texture.py from NASA's
// public-domain GEBCO elevation raster (ocean is exactly 0 there, so one
// dataset yields both the coastline mask and the relief).
//
// The two layers are deliberately different resolutions: coastlines are what
// make the globe recognisable, so they get the finer grid, while elevation is
// only ever used as a dither density and survives being coarse.
namespace EarthTexture {

constexpr int kMaskWidth = 384;
constexpr int kMaskHeight = 192;
constexpr int kElevWidth = 192;
constexpr int kElevHeight = 96;

// Equirectangular, row 0 = 90N, column 0 = 180W. One bit per cell, MSB first.
extern const uint8_t kLandMask[9216];
// Same projection, two 4-bit cells per byte (high nibble = even column).
// Already gamma-corrected (0.45) and quantised to 16 levels.
extern const uint8_t kElevation[9216];

// True when the equirectangular cell is land.
inline bool isLand(const int x, const int y) {
  const int index = y * kMaskWidth + x;
  return (kLandMask[index >> 3] >> (7 - (index & 7))) & 1;
}

// Terrain height at an equirectangular cell, 0 (sea level) to 15 (highest).
inline uint8_t elevation(const int x, const int y) {
  const uint8_t packed = kElevation[(y * kElevWidth + x) >> 1];
  return (x & 1) ? (packed & 0x0F) : (packed >> 4);
}

}  // namespace EarthTexture
