#pragma once

#include <cstdint>

// Embedded photograph of the full moon (NASA/GSFC, public domain), cropped to
// the disc and contrast-stretched. Generated by scripts/gen_moon_texture.py.
//
// Stored at 4 bits per sample, two per byte: the disc is dithered to 1-bit
// when drawn, so 16 grey levels is visually identical to 256 at half the
// flash. Contrast (gamma 1.6) is baked in here rather than applied at draw
// time, keeping the per-pixel path on the device free of it.
constexpr int kMoonTextureSize = 100;

// Row-major, high nibble = even column.
extern const uint8_t kMoonTexturePacked[5000];

// Surface brightness at a texture cell, 0 (darkest) to 15 (brightest).
inline uint8_t moonSample(const int x, const int y) {
  const uint8_t byte = kMoonTexturePacked[(y * kMoonTextureSize + x) >> 1];
  return (x & 1) ? (byte & 0x0F) : (byte >> 4);
}
