"""Regenerate src/images/MoonTexture.{h,cpp} as 4-bit, with contrast applied.

Reads the existing embedded array and transforms it in place rather than
re-deriving from the NASA source, so the crop, framing and percentile stretch
that were tuned by eye earlier carry over exactly.

Two changes:
  * gamma > 1 darkens the mid-tones, so the maria read as dark rather than
    washed out and the disc carries similar weight to the Earth globe.
  * 4 bits per sample instead of 8. The texture is dithered to 1-bit at draw
    time and Floyd-Steinberg diffuses quantisation error along with everything
    else, so 16 levels is indistinguishable from 256 and costs half as much.

Usage: python3 scripts/gen_moon_texture.py [gamma]
"""
import re
import sys

N = 100
GAMMA = float(sys.argv[1]) if len(sys.argv) > 1 else 1.6
SRC = 'src/images/MoonTexture.cpp'
HDR = 'src/images/MoonTexture.h'


def read_existing():
    body = open(SRC).read()
    if 'kMoonTexturePacked' in body:
        raise SystemExit('MoonTexture.cpp is already 4-bit; regenerate from the 8-bit original instead.')
    values = [int(v) for v in re.findall(r'\b(\d{1,3})\b', body.split('{', 1)[1])]
    values = values[-N * N:]
    if len(values) != N * N:
        raise SystemExit(f'expected {N * N} samples, found {len(values)}')
    return values


def main():
    values = read_existing()
    nibbles = [min(15, max(0, round(((v / 255.0) ** GAMMA) * 15.0))) for v in values]
    packed = bytearray()
    for i in range(0, len(nibbles), 2):
        packed.append((nibbles[i] << 4) | nibbles[i + 1])
    print(f'gamma {GAMMA}, {len(values)} samples -> {len(packed)} bytes '
          f'(was {len(values)}, saving {len(values) - len(packed)})')

    with open(HDR, 'w') as f:
        f.write(f'''#pragma once

#include <cstdint>

// Embedded photograph of the full moon (NASA/GSFC, public domain), cropped to
// the disc and contrast-stretched. Generated by scripts/gen_moon_texture.py.
//
// Stored at 4 bits per sample, two per byte: the disc is dithered to 1-bit
// when drawn, so 16 grey levels is visually identical to 256 at half the
// flash. Contrast (gamma {GAMMA}) is baked in here rather than applied at draw
// time, keeping the per-pixel path on the device free of it.
constexpr int kMoonTextureSize = {N};

// Row-major, high nibble = even column.
extern const uint8_t kMoonTexturePacked[{len(packed)}];

// Surface brightness at a texture cell, 0 (darkest) to 15 (brightest).
inline uint8_t moonSample(const int x, const int y) {{
  const uint8_t byte = kMoonTexturePacked[(y * kMoonTextureSize + x) >> 1];
  return (x & 1) ? (byte & 0x0F) : (byte >> 4);
}}
''')

    with open(SRC, 'w') as f:
        f.write('#include "MoonTexture.h"\n\n')
        f.write(f'const uint8_t kMoonTexturePacked[{len(packed)}] = {{\n')
        for i in range(0, len(packed), 20):
            f.write('    ' + ','.join(str(b) for b in packed[i:i + 20]) + ',\n')
        f.write('};\n')
    print('wrote MoonTexture.h / MoonTexture.cpp')


main()
