"""Generate src/images/EarthTexture.{h,cpp} from NASA GEBCO elevation.

Two layers, because they want different resolutions:
  * land mask, 384x192, 1 bit  -> coastlines, where recognition lives
  * elevation, 192x96,  4 bits -> terrain texture, which gets dithered anyway

Sized by eye against rendered globes rather than by principle: 512x256 was
visibly no better at the disc sizes this actually draws at, and cost 14KB more
of a nearly full flash partition.

Elevation is gamma-lifted at build time (most land is low, so a linear ramp
leaves continents nearly blank) and quantised to 16 levels, so the firmware
just maps a nibble to an ink density.
"""
import numpy as np
from PIL import Image

Image.MAX_IMAGE_PIXELS = None
SRC = '/tmp/gebco_elev.png'
MASK_W, MASK_H = 384, 192
ELEV_W, ELEV_H = 192, 96
GAMMA = 0.45
OUT_DIR = '/Users/mgmtbook/Documents/retroink/src/images/'


def main():
    src = Image.open(SRC).convert('L')
    mask_img = np.asarray(src.resize((MASK_W, MASK_H), Image.BOX)).astype(int)
    elev_img = np.asarray(src.resize((ELEV_W, ELEV_H), Image.BOX)).astype(float)

    land = mask_img > 0
    print(f'land fraction {land.mean():.3f} (Earth is ~0.29)')

    e = np.clip(elev_img / 239.0, 0.0, 1.0) ** GAMMA
    nib = np.clip(np.round(e * 15.0), 0, 15).astype(int)

    # Pack the mask, MSB first within each byte, row-major.
    mask_bytes = bytearray()
    for y in range(MASK_H):
        acc, n = 0, 0
        for x in range(MASK_W):
            acc = (acc << 1) | (1 if land[y, x] else 0)
            n += 1
            if n == 8:
                mask_bytes.append(acc); acc, n = 0, 0
    # Pack elevation, two nibbles per byte, high nibble first.
    elev_bytes = bytearray()
    for y in range(ELEV_H):
        for x in range(0, ELEV_W, 2):
            elev_bytes.append((nib[y, x] << 4) | nib[y, x + 1])

    print(f'mask {len(mask_bytes)} bytes, elevation {len(elev_bytes)} bytes, '
          f'total {(len(mask_bytes)+len(elev_bytes))/1024:.1f} KB')

    with open(OUT_DIR + 'EarthTexture.h', 'w') as f:
        f.write(f'''#pragma once

#include <cstdint>

// Embedded Earth map, generated by scripts/gen_earth_texture.py from NASA's
// public-domain GEBCO elevation raster (ocean is exactly 0 there, so one
// dataset yields both the coastline mask and the relief).
//
// The two layers are deliberately different resolutions: coastlines are what
// make the globe recognisable, so they get the finer grid, while elevation is
// only ever used as a dither density and survives being coarse.
namespace EarthTexture {{

constexpr int kMaskWidth = {MASK_W};
constexpr int kMaskHeight = {MASK_H};
constexpr int kElevWidth = {ELEV_W};
constexpr int kElevHeight = {ELEV_H};

// Equirectangular, row 0 = 90N, column 0 = 180W. One bit per cell, MSB first.
extern const uint8_t kLandMask[{len(mask_bytes)}];
// Same projection, two 4-bit cells per byte (high nibble = even column).
// Already gamma-corrected ({GAMMA}) and quantised to 16 levels.
extern const uint8_t kElevation[{len(elev_bytes)}];

// True when the equirectangular cell is land.
inline bool isLand(const int x, const int y) {{
  const int index = y * kMaskWidth + x;
  return (kLandMask[index >> 3] >> (7 - (index & 7))) & 1;
}}

// Terrain height at an equirectangular cell, 0 (sea level) to 15 (highest).
inline uint8_t elevation(const int x, const int y) {{
  const uint8_t packed = kElevation[(y * kElevWidth + x) >> 1];
  return (x & 1) ? (packed & 0x0F) : (packed >> 4);
}}

}}  // namespace EarthTexture
''')

    def emit(name, data, f):
        f.write(f'const uint8_t {name}[{len(data)}] = {{\n')
        for i in range(0, len(data), 20):
            f.write('    ' + ','.join(str(b) for b in data[i:i + 20]) + ',\n')
        f.write('};\n\n')

    with open(OUT_DIR + 'EarthTexture.cpp', 'w') as f:
        f.write('#include "EarthTexture.h"\n\nnamespace EarthTexture {\n\n')
        emit('kLandMask', mask_bytes, f)
        emit('kElevation', elev_bytes, f)
        f.write('}  // namespace EarthTexture\n')
    print('wrote EarthTexture.h / EarthTexture.cpp')


main()
